apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: revision
      value: v8.0.0
    - name: url
      value: https://github.com/OSMadmin/LCM.git
    